spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:default}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:admin}?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useTimezone=true&serverTimezone=Asia/Shanghai&connectTimeout=2000&socketTimeout=600000&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
  security:
    user-class: org.ifinalframework.console.sso.model.User
  flyway:
    schemas: admin
    clean-schema-history-on-after-migrate-operation-finish: true
    enabled: true
final.security.user-class: ${spring.security.user-class}
