spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:default}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useTimezone=true&serverTimezone=Asia/Shanghai&connectTimeout=2000&socketTimeout=600000&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  security:
    basic:
      enable: true
    bearer:
      enable: false
    remember-me:
      enable: true
      always-remember: true
    anonymous:
      enable: true
      authorities:
        - 'default:tags:list'
        - 'default:organizations:list'
        - 'default:students:create'
        - 'default:app-versions:create'
    logout:
      enable: true
    user-class: org.ifinalframework.console.sso.domain.security.SecurityUser
  flyway:
    schemas: admin
    clean-schema-history-on-after-migrate-operation-finish: true
    enabled: true
final.security.user-class: ${spring.security.user-class}
