spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useTimezone=true&serverTimezone=Asia/Shanghai&connectTimeout=2000&socketTimeout=600000&allowPublicKeyRetrieval=true
    username: root
    password: '@Aa000000'
  flyway:
    schemas: admin
    clean-schema-history-on-after-migrate-operation-finish: true
    enabled: true
logging:
  level:
    org.ifinalframework.admin.repository: debug